/* K2P */

#define BOARD_PID		"CVR-S800"
#define BOARD_NAME		"CVR-S800"
#define BOARD_DESC		"CVR-S800 Router"
#define BOARD_VENDOR_NAME	"HUIGU"
#define BOARD_VENDOR_URL	"http://www.huigu.com/"
#define BOARD_MODEL_URL		"http://www.huigu.com/"
#define BOARD_BOOT_TIME		30
#define BOARD_FLASH_TIME	120
#undef BOARD_GPIO_BTN_FN1
#define BOARD_GPIO_BTN_RESET 18
#undef BOARD_GPIO_BTN_WPS
#undef  BOARD_GPIO_LED_ALL
#undef  BOARD_GPIO_LED_WIFI
#undef  BOARD_GPIO_LED_SW2G
#undef  BOARD_GPIO_LED_SW5G
#define  BOARD_GPIO_LED_POWER	5
#undef  BOARD_GPIO_LED_LAN
#undef BOARD_GPIO_LED_WAN
#define BOARD_GPIO_LED_USB	4
#undef BOARD_GPIO_LED_ROUTER
#undef  BOARD_GPIO_PWR_USB
#define BOARD_HAS_5G_11AC	0
#define BOARD_NUM_ANT_5G_TX	0
#define BOARD_NUM_ANT_5G_RX	0
#define BOARD_NUM_ANT_2G_TX	0
#define BOARD_NUM_ANT_2G_RX	0
#define BOARD_NUM_ETH_LEDS	5
#define BOARD_HAS_EPHY_L1000	1
#define BOARD_HAS_EPHY_W1000	1
#define BOARD_NUM_UPHY_USB3	1
#define BOARD_USB_PORT_SWAP	0
